// Socket events
export const INIT_GAME = 'init-game'
export const JOIN_GAME = 'join-game'
export const PLAYER_JOINED = 'player-joined'
export const START_GAME = 'start-game'
export const HOST_START_GAME = 'host-start-game'
export const START_QUESTION = 'start-question'
export const HOST_START_QUESTION = 'host-start-question'
export const SEND_ANSWER = 'send-answer'
export const PLAYER_ANSWERED = 'player-answered'
export const END_GAME = 'end-game'
export const HOST_END_GAME = 'host-end-game'
export const OUT_GAME = 'out-game'
export const PLAYER_OUT = 'player-out'
